### ISSUE TITLE
cannot cast to ambeo soundbar

### ISSUE THREAD

**Issue by tuupos** [faizpuru/ha-ambeo_soundbar#24]
although the ambeo soundbar (mini) appears in my cast integration in home assistant , i cannot get it to work with cast.

![image](https://github.com/user-attachments/assets/82a30238-bbfc-4a1e-9380-cb8ee64b88c0)

I Want a TTS message played on my soundbar but cannot get it to work. 

error message:

_`Actie media_player/turn_on kon niet worden uitgevoerd. CastMediaPlayerEntity._start_app Failed: Failed to execute start app CC1AD845.`_

**Comment by faizpuru** [comment]
The Ambeo soundbar integration with TTS seems to be failing. This functionality is not handled by the soundbar integration itself, but rather by the Google Cast integration in Home Assistant.
For detailed setup instructions, please check:

The Google Cast integration documentation: https://www.home-assistant.io/integrations/cast/
The specific TTS documentation for Google Cast devices: https://www.home-assistant.io/integrations/tts/#google-cast-devices
I'm closing this issue since it's related to the Google Cast integration

**Comment by tuupos** [comment]
Got it working through google cast in home assistant! Again, thanks for pointing me in the right direction.
